In [1]:
import pandas as pd
import numpy as np

In [2]:
data_2018_2020 = pd.read_excel('2018-2020.xlsx')
data_2020_2022 = pd.read_excel('2020-2022.xlsx')
data_2022_2024 = pd.read_excel('2022-2024.xlsx')

/opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [33]:
data_2018_2020

,번호,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액
0,1,2020/05/27,218410,RFHIC,KOSDAQ,직접,취득,2020/05/28,2020/11/27,132275,5000000000,132275,100.0,4636499650
1,2,2020/05/26,25900,동화기업,KOSDAQ,직접,처분,2020/05/27,2020/05/27,250000,6400000000,250000,100.0,6080000000
2,3,2020/05/25,253590,네오셈,KOSDAQ,신탁,취득,2020/05/25,2020/11/24,0,2000000000,571366,0.0,1283324315
3,4,2020/05/25,79370,제우스,KOSDAQ,신탁,취득,2020/05/26,2021/05/25,0,2000000000,148412,0.0,1870236200
4,5,2020/05/20,25900,동화기업,KOSDAQ,직접,처분,2020/05/21,2020/05/21,500000,13200000000,500000,100.0,12540000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1192,1193,2018/06/01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2020/05/31,0,1000000000,16800,0.0,38690580
1193,1194,2018/06/01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,1000000000,51500,0.0,155690930
1194,1195,2018/06/01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,45200,0.0,199984125
1195,1196,2018/05/31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,470309,100.0,934335885
1196,1197,2018/05/30,3000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,1510786,100.0,42851934104

In [34]:
data_2020_2022

,번호,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액
0,1,2022/05/27,003550,LG,KOSPI,신탁,취득,2022/05/30,2024/12/31,0,500000000000,5590677.0,0.0,4.620222e+11
1,2,2022/05/27,003670,포스코퓨처엠,KOSPI,직접,취득,2022/05/30,2022/08/29,75187,9999871000,75187.0,100.0,9.645326e+09
2,3,2022/05/26,375500,DL이앤씨,KOSPI,신탁,취득,2022/05/26,2022/11/25,0,29000000000,647077.0,0.0,2.687100e+10
3,4,2022/05/26,37550L,DL이앤씨2우(전환),KOSPI,신탁,취득,2022/05/26,2022/11/25,0,29000000000,32299.0,0.0,1.076557e+09
4,5,2022/05/26,37550L,DL이앤씨2우(전환),KOSPI,신탁,취득,,,0,0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
786,787,2020/06/11,227840,현대코퍼레이션홀딩스,KOSPI,신탁,취득,2020/06/12,2020/12/11,0,3000000000,290000.0,0.0,2.985962e+09
787,788,2020/06/10,251370,와이엠티,KOSDAQ,직접,처분,2020/06/11,2020/06/11,80570,2167333000,80570.0,100.0,2.167333e+09
788,789,2020/06/05,006800,미래에셋증권,KOSPI,직접,취득,2020/06/08,2020/09/07,16000000,108600000000,16000000.0,100.0,1.108164e+11
789,790,2020/06/01,302920,더콘텐츠온,KONEX,신탁,취득,2020/06/01,2020/11/30,0,100000000,1188.0,0.0,1.241460e+07
790,791,2020/05/29,003410,쌍용C&E,KOSPI,신탁,취득,2020/06/01,2020/12/01,0,30000000000,3014405.0,0.0,1.568692e+10

In [35]:
data_2022_2024

,번호,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액
0,1,2024/05/27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0,0.0,0
1,2,2024/05/24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,0,0.0,0
2,3,2024/05/24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,0,0.0,0
3,4,2024/05/24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0,0.0,0
4,5,2024/05/24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,974,2022/06/07,086900,메디톡스,KOSDAQ,직접,취득,2022/06/08,2022/09/05,39777,4999968900,39777,100.0,4574169500
974,975,2022/06/03,039440,에스티아이,KOSDAQ,신탁,취득,2022/06/03,2022/12/02,0,3000000000,159600,0.0,2984925950
975,976,2022/06/02,307870,비투엔,KOSDAQ,신탁,취득,2022/06/02,2022/12/02,0,2000000000,713194,0.0,1448972590
976,977,2022/05/31,236810,엔비티,KOSDAQ,신탁,취득,2022/06/02,2022/12/01,0,3500000000,430273,0.0,3492828520
977,978,2022/05/30,017650,대림제지,KOSDAQ,직접,취득,2022/05/31,2022/08/30,100000,959000000,100000,100.0,855555160

In [3]:
print(data_2018_2020.shape)
print(data_2020_2022.shape)
print(data_2022_2024.shape)

(1197, 14)
(791, 14)
(978, 14)

In [288]:
full_data = pd.concat([data_2018_2020, data_2020_2022, data_2022_2024], ignore_index=True)

In [289]:
full_data.columns

Index(['번호', '공시일', '종목코드', '종목명', '시장구분', '직접/신탁', '취득/처분', '취득(처분)예정기간_시작일',
       '취득(처분)예정기간_종료일', '신고내역_수량', '신고내역_금액', '체결내역(누계)_수량',
       '체결내역(누계)_체결수량비율', '체결내역(누계)_금액'],
      dtype='object')

In [290]:
full_data = full_data.sort_values(by='공시일', ascending=True).reset_index()
full_data = full_data.drop(columns=['index','번호'])

In [291]:
full_data['종목코드'] = full_data['종목코드'].astype(str).str.zfill(6)
full_data

,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액
0,2018/05/30,003000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,1510786.0,100.0,4.285193e+10
1,2018/05/31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,470309.0,100.0,9.343359e+08
2,2018/06/01,232140,와이씨,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,2000000000,437256.0,0.0,1.993199e+09
3,2018/06/01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,45200.0,0.0,1.999841e+08
4,2018/06/01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2020/05/31,0,1000000000,16800.0,0.0,3.869058e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,2024/05/24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,0.0,0.0,0.000000e+00
2962,2024/05/24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,0.0,0.0,0.000000e+00
2963,2024/05/24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00
2964,2024/05/24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00
2965,2024/05/27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00

In [292]:
company_list = full_data['종목명'].unique()
print(len(company_list))

1105

In [293]:
full_data.to_csv('full_data.csv', index=False, encoding='utf-8')

In [392]:
full_data = pd.read_csv('full_data.csv')

In [295]:
import requests
import pandas as pd
from datetime import datetime

# API key and base URL
API_KEY = '6e613b286881d7618be53b0237ead54a9751e26e'
BASE_URL_Multi= "https://opendart.fss.or.kr/api/fnlttMultiAcnt.json	"
BASE_URL_SINGLE = "https://opendart.fss.or.kr/api/fnlttSinglAcntAll.json"

In [296]:
def get_data(url, params):
    print(params)
    response = requests.get(url, params=params)
    data = response.json()
    print(data)
    if 'Data' in data and 'Data' in data['Data']:
        return pd.DataFrame(data['Data']['Data'])
    elif 'Data' in data:
        return pd.DataFrame(data['Data'])
    else:
        print("Error fetching data")
        return None

In [297]:
import pandas as pd
import xmltodict

def unique_code_xml_to_dataframe(xml_file):
    # XML 파일을 읽기
    with open(xml_file, 'r', encoding='utf-8') as file:
        xml_content = file.read()
    
    # XML을 파이썬 딕셔너리로 변환
    xml_dict = xmltodict.parse(xml_content)
    
    # 'result' 안의 'list'를 추출
    records = xml_dict['result']['list']
    
    # DataFrame 생성
    df = pd.DataFrame(records)
    
    return df

In [298]:
xml_file = 'CORPCODE.xml'

# XML을 DataFrame으로 변환
unique_code_df = unique_code_xml_to_dataframe(xml_file)
unique_code_df

       corp_code          corp_name stock_code modify_date
0       00434003                 다코       None    20170630
1       00434456               일산약품       None    20170630
2       00430964              굿앤엘에스       None    20170630
3       00432403               한라판지       None    20170630
4       00388953  크레디피아제이십오차유동화전문회사       None    20170630
...          ...                ...        ...         ...
106927  01835069                아로하       None    20240510
106928  01839199            호프인터내셔널       None    20240510
106929  01823392            포스텍네트웍스       None    20240510
106930  01837003         농업회사법인복순도가       None    20240510
106931  01785904           스튜디오에피소드       None    20240510

[106932 rows x 4 columns]

In [393]:
full_data = full_data.drop_duplicates(subset=['종목명','종목코드','공시일'])
full_data

,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액
0,2018/05/30,003000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,1510786.0,100.0,4.285193e+10
1,2018/05/31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,470309.0,100.0,9.343359e+08
2,2018/06/01,232140,와이씨,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,2000000000,437256.0,0.0,1.993199e+09
3,2018/06/01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,45200.0,0.0,1.999841e+08
5,2018/06/01,080220,제주반도체,KOSDAQ,직접,취득,2018/06/04,2018/09/01,100000,472000000,100000.0,100.0,5.059698e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,2024/05/24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,0.0,0.0,0.000000e+00
2962,2024/05/24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,0.0,0.0,0.000000e+00
2963,2024/05/24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00
2964,2024/05/24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00
2965,2024/05/27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00

In [394]:
quarter_code = {
    1: '11013',
    2: '11012',
    3: '11014',
    4: '11011'
}

full_data['공시일'] = pd.to_datetime(full_data['공시일'])
full_data['분기'] = pd.to_datetime(full_data['공시일']).apply(lambda x: (x.month-1)//3+1)
full_data['사업연도'] = full_data['공시일'].dt.year

def get_previous_quarter(x):
    current_quarter = (x.month-1)//3 + 1
    if current_quarter == 1:
        previous_quarter = 4
    else:
        previous_quarter = current_quarter - 1
    return previous_quarter

full_data['직전분기'] = full_data['공시일'].apply(get_previous_quarter)
full_data['직전분기코드'] = full_data['직전분기'].map(quarter_code)


full_data

,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액,분기,사업연도,직전분기,직전분기코드
0,2018-05-30,003000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,1510786.0,100.0,4.285193e+10,2,2018,1,11013
1,2018-05-31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,470309.0,100.0,9.343359e+08,2,2018,1,11013
2,2018-06-01,232140,와이씨,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,2000000000,437256.0,0.0,1.993199e+09,2,2018,1,11013
3,2018-06-01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,45200.0,0.0,1.999841e+08,2,2018,1,11013
5,2018-06-01,080220,제주반도체,KOSDAQ,직접,취득,2018/06/04,2018/09/01,100000,472000000,100000.0,100.0,5.059698e+08,2,2018,1,11013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,2024-05-24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2962,2024-05-24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2963,2024-05-24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2964,2024-05-24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2965,2024-05-27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,2024,1,11013

In [343]:
# def concat_unique_code(company_df, unique_code_df):
#     company_df = company_df.merge(unique_code_df, left_on='종목명', right_on='corp_name', how='left')
#     return company_df

In [344]:
# def concat_unique_code_by_stock_code(company_df, unique_code_df):
#     company_df = company_df.merge(unique_code_df, left_on='종목코드', right_on='stock_code', how='left')
#     return company_df

In [345]:
# full_data = concat_unique_code(full_data, unique_code_df)

In [346]:
full_data

,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액,분기,사업연도,직전분기,직전분기코드
0,2018-05-30,003000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,1510786.0,100.0,4.285193e+10,2,2018,1,11013
1,2018-05-31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,470309.0,100.0,9.343359e+08,2,2018,1,11013
2,2018-06-01,232140,와이씨,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,2000000000,437256.0,0.0,1.993199e+09,2,2018,1,11013
3,2018-06-01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,45200.0,0.0,1.999841e+08,2,2018,1,11013
5,2018-06-01,080220,제주반도체,KOSDAQ,직접,취득,2018/06/04,2018/09/01,100000,472000000,100000.0,100.0,5.059698e+08,2,2018,1,11013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,2024-05-24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2962,2024-05-24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2963,2024-05-24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2964,2024-05-24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2965,2024-05-27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,2024,1,11013

In [305]:
# full_data = concat_unique_code_by_stock_code(full_data, unique_code_df)

In [306]:
# full_data

,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,...,직전분기,직전분기코드,corp_code_x,corp_name_x,stock_code_x,modify_date_x,corp_code_y,corp_name_y,stock_code_y,modify_date_y
0,2018-05-30,003000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,...,1,11013,00123718,부광약품,003000,20240403,00123718,부광약품,003000,20240403
1,2018-05-31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,...,1,11013,00411905,테라셈,182690,20221017,00411905,테라셈,182690,20221017
2,2018-06-01,232140,와이씨,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,2000000000,...,1,11013,01109539,와이씨,232140,20240425,01109539,와이씨,232140,20240425
3,2018-06-01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,...,1,11013,00164502,현대공업,170030,20230418,00164502,현대공업,170030,20230418
4,2018-06-01,080220,제주반도체,KOSDAQ,직접,취득,2018/06/04,2018/09/01,100000,472000000,...,1,11013,00447487,제주반도체,080220,20221207,00447487,제주반도체,080220,20221207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,2024-05-24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,...,1,11013,00614478,휴메딕스,200670,20220906,00614478,휴메딕스,200670,20220906
3353,2024-05-24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,...,1,11013,01033591,큐알티,405100,20240227,01033591,큐알티,405100,20240227
3354,2024-05-24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,...,1,11013,00228059,휴온스글로벌,084110,20221128,00228059,휴온스글로벌,084110,20221128
3355,2024-05-24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,...,1,11013,01159853,휴온스,243070,20221007,01159853,휴온스,243070,20221007
3356,2024-05-27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,...,1,11013,00561732,아스플로,159010,20220603,00561732,아스플로,159010,20220603

In [307]:
# full_data['corp_code'] = full_data['corp_code_x'].combine_first(full_data['corp_code_y'])

In [347]:
full_data

,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액,분기,사업연도,직전분기,직전분기코드
0,2018-05-30,003000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,1510786.0,100.0,4.285193e+10,2,2018,1,11013
1,2018-05-31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,470309.0,100.0,9.343359e+08,2,2018,1,11013
2,2018-06-01,232140,와이씨,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,2000000000,437256.0,0.0,1.993199e+09,2,2018,1,11013
3,2018-06-01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,45200.0,0.0,1.999841e+08,2,2018,1,11013
5,2018-06-01,080220,제주반도체,KOSDAQ,직접,취득,2018/06/04,2018/09/01,100000,472000000,100000.0,100.0,5.059698e+08,2,2018,1,11013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,2024-05-24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2962,2024-05-24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2963,2024-05-24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2964,2024-05-24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2965,2024-05-27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,2024,1,11013

In [309]:
# list_to_remove_index = full_data.loc[full_data['corp_code'].isna()].index.tolist()
# list_to_remove = full_data.loc[full_data['corp_code'].isna()]
# full_data = full_data.drop(list_to_remove_index)
# full_data.loc[full_data['corp_code'].isna()]

Empty DataFrame
Columns: [공시일, 종목코드, 종목명, 시장구분, 직접/신탁, 취득/처분, 취득(처분)예정기간_시작일, 취득(처분)예정기간_종료일, 신고내역_수량, 신고내역_금액, 체결내역(누계)_수량, 체결내역(누계)_체결수량비율, 체결내역(누계)_금액, 분기, 사업연도, 직전분기, 직전분기코드, corp_code_x, corp_name_x, stock_code_x, modify_date_x, corp_code_y, corp_name_y, stock_code_y, modify_date_y, corp_code]
Index: []

[0 rows x 26 columns]

In [348]:
full_data

,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액,분기,사업연도,직전분기,직전분기코드
0,2018-05-30,003000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,1510786.0,100.0,4.285193e+10,2,2018,1,11013
1,2018-05-31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,470309.0,100.0,9.343359e+08,2,2018,1,11013
2,2018-06-01,232140,와이씨,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,2000000000,437256.0,0.0,1.993199e+09,2,2018,1,11013
3,2018-06-01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,45200.0,0.0,1.999841e+08,2,2018,1,11013
5,2018-06-01,080220,제주반도체,KOSDAQ,직접,취득,2018/06/04,2018/09/01,100000,472000000,100000.0,100.0,5.059698e+08,2,2018,1,11013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,2024-05-24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2962,2024-05-24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2963,2024-05-24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2964,2024-05-24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2965,2024-05-27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,2024,1,11013

In [311]:
# full_data = full_data.drop(columns=['corp_code_x','corp_code_y','corp_name_x','stock_code_x','modify_date_x','corp_name_y','stock_code_y','modify_date_y'], inplace=False)

In [395]:
index_to_drop = full_data[full_data['시장구분'] == "KONEX"].index
full_data = full_data.drop(index_to_drop)

In [396]:
full_data

,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액,분기,사업연도,직전분기,직전분기코드
0,2018-05-30,003000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,1510786.0,100.0,4.285193e+10,2,2018,1,11013
1,2018-05-31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,470309.0,100.0,9.343359e+08,2,2018,1,11013
2,2018-06-01,232140,와이씨,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,2000000000,437256.0,0.0,1.993199e+09,2,2018,1,11013
3,2018-06-01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,45200.0,0.0,1.999841e+08,2,2018,1,11013
5,2018-06-01,080220,제주반도체,KOSDAQ,직접,취득,2018/06/04,2018/09/01,100000,472000000,100000.0,100.0,5.059698e+08,2,2018,1,11013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,2024-05-24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2962,2024-05-24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2963,2024-05-24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2964,2024-05-24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,2024,1,11013
2965,2024-05-27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,2024,1,11013

### Test

In [312]:
def get_company_info_single(unique_code, year, quarter):
    print(unique_code, quarter, year)
    params = {
        'crtfc_key': API_KEY,
        'corp_code': unique_code,
        'bsns_year': year,
        'reprt_code': quarter,
        'fs_div': 'OFS'
    }
    return get_data(BASE_URL_SINGLE, params)

In [313]:
params = full_data.iloc[2][['corp_code','사업연도','직전분기코드']].tolist()
get_company_info_single(*params)

01109539 11013 2018
{'crtfc_key': '6e613b286881d7618be53b0237ead54a9751e26e', 'corp_code': '01109539', 'bsns_year': 2018, 'reprt_code': '11013', 'fs_div': 'OFS'}

In [314]:
!pip install opendartreader

Requirement already satisfied: opendartreader in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (0.2.3)
Requirement already satisfied: pandas>=0.19.2 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from opendartreader) (2.0.3)
Requirement already satisfied: requests>=2.3.0 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from opendartreader) (2.31.0)
Requirement already satisfied: requests-file in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from opendartreader) (2.0.0)
Requirement already satisfied: lxml in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from opendartreader) (5.2.1)
Requirement already satisfied: beautifulsoup4 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from opendartreader) (4.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from pandas>=0.19.2->opendartreader) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from pandas>=0.19.2->opendartreader) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from pandas>=0.19.2->opendartreader) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from pandas>=0.19.2->opendartreader) (1.24.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from requests>=2.3.0->opendartreader) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from requests>=2.3.0->opendartreader) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from requests>=2.3.0->opendartreader) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from requests>=2.3.0->opendartreader) (2024.2.2)
Requirement already satisfied: soupsieve>1.2 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from beautifulsoup4->opendartreader) (2.5)
Requirement already satisfied: six>=1.5 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=0.19.2->opendartreader) (1.16.0)

In [351]:
import OpenDartReader

api_key = '6e613b286881d7618be53b0237ead54a9751e26e'

dart = OpenDartReader(api_key)

In [352]:

# for index, row in search_company_list.iterrows():
row = full_data.iloc[80]
corp = row['종목코드']
bsns_year = row['사업연도']
reprt_code = row['직전분기코드']
df = dart.finstate(corp, bsns_year, reprt_code)
filterd_df = df.loc[df['account_nm'].isin(['매출액', '영업이익', '당기순이익', '유동자산']) & (df['fs_nm'] == '재무제표')]
print(filterd_df.columns)
pivot_df = filterd_df.pivot(index = 'stock_code',columns='account_nm', values=['thstrm_amount','frmtrm_amount'])
pivot_df.columns = ['_'.join(col) for col in pivot_df.columns]
pivot_df = pivot_df.reset_index()
pivot_df['사업연도'] = bsns_year
pivot_df['직전분기코드'] = reprt_code
pivot_df

Index(['rcept_no', 'reprt_code', 'bsns_year', 'corp_code', 'stock_code',
       'fs_div', 'fs_nm', 'sj_div', 'sj_nm', 'account_nm', 'thstrm_nm',
       'thstrm_dt', 'thstrm_amount', 'frmtrm_nm', 'frmtrm_dt', 'frmtrm_amount',
       'ord', 'currency', 'thstrm_add_amount', 'frmtrm_add_amount'],
      dtype='object')

,stock_code,thstrm_amount_당기순이익,thstrm_amount_매출액,thstrm_amount_영업이익,thstrm_amount_유동자산,frmtrm_amount_당기순이익,frmtrm_amount_매출액,frmtrm_amount_영업이익,frmtrm_amount_유동자산,사업연도,직전분기코드
0,099190,"5,477,333,371","35,292,015,748","4,763,197,199","88,173,202,882","6,321,844,156","32,962,458,182","6,807,136,005","86,572,164,223",2018,11012

In [361]:
row = full_data.iloc[157]
row

공시일                2018-10-25 00:00:00
종목코드                            029780
종목명                               삼성카드
시장구분                             KOSPI
직접/신탁                               직접
취득/처분                               취득
취득(처분)예정기간_시작일              2018/10/26
취득(처분)예정기간_종료일              2019/01/25
신고내역_수량                        1400000
신고내역_금액                    47250000000
체결내역(누계)_수량                  1400000.0
체결내역(누계)_체결수량비율                  100.0
체결내역(누계)_금액              47323537500.0
분기                                   4
사업연도                              2018
직전분기                                 3
직전분기코드                           11014
Name: 176, dtype: object

In [391]:
full_data.shape

(2669,)

In [371]:

# for index, row in search_company_list.iterrows():
result_df = pd.DataFrame()
no_corp_code_list = []

for index, row in full_data.iterrows():
    comp_name = row['종목명']
    corp = row['종목코드']
    bsns_year = row['사업연도']
    reprt_code = row['직전분기코드']
    corp_code = dart.find_corp_code(cㅈorp)
    if(corp is None or bsns_year is None or reprt_code is None or corp_code is None):
        print("None value found")
        print(comp_name, corp, bsns_year, reprt_code, corp_code)
        no_corp_code_list.append({'comp_name':comp_name, 'corp':corp, 'bsns_year':bsns_year, 'reprt_code':reprt_code, 'corp_code':corp_code})
        continue
    df = dart.finstate(corp, bsns_year, reprt_code)
    print(index)
    # print(index)
    if('account_nm' not in df):
        continue
    filterd_df = df.loc[df['account_nm'].isin(['매출액', '영업이익', '당기순이익', '유동자산']) & (df['fs_nm'] == '재무제표')]
    pivot_df = filterd_df.pivot(index = 'stock_code',columns='account_nm', values=['thstrm_amount','frmtrm_amount'])
    pivot_df.columns = ['_'.join(col) for col in pivot_df.columns]
    pivot_df = pivot_df.reset_index()
    pivot_df['사업연도'] = bsns_year
    pivot_df['직전분기코드'] = reprt_code
    pivot_df['종목명'] = comp_name
    result_df = pd.concat([result_df, pivot_df], ignore_index=True)

result_df

0
1
2
3
5
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
46
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
66
67
68
69
70
71
72
73
74
75
77
78
79
82
83
84
85
86
87
90
91
92
93
94
95
96
97
98
99
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

100
101
102
103
104
105
107
108
109
111
112
113
114
115
117
118
119
120
122
123
124
125
126
127
129
130
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

155
156
None value found
신영증권우 001725 2018 11014 None
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

158
159
160
161
162
163
164
165
None value found
대교우B 019685 2018 11014 None
168
170
171
172
173
174
175
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

176
177
178
179
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
205
207
208
209
210
211
212
214
216
221
222
223
225
226
227
228
229
230
231
232
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
258
259
260
261
262
263
264
265
266
269
271
274
275
276
277
279
280
281
282
283
284
285
286
287
289
290
291
293
295
297
None value found
현대차우 005385 2018 11014 None
None value found
현대차3우B 005389 2018 11014 None
None value found
현대차2우B 005387 2018 11014 None
301
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

302
303
304
None value found
한국유리우 002005 2018 11014 None
306
307
308
309
310
311
312
313
314
315
316
317
320
321
322
323
324
327
328
330
332
333
335
336
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

337
338
None value found
유화증권우 003465 2018 11014 None
340
341
342
343
344
345
347
348
349
350
351
352
353
354
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

356
357
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

358
359
360
361
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

362
363
364
365
366
367
368
369
370
371
372
374
375
376
377
378
379
380
381
382
383
384
386
387
388
389
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

390
391
393
394
395
396
397
398
399
402
403
404
405
406
407
408
409
410
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

411
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

429
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

430
431
434
435
437
438
439
440
441
442
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

443
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

444
445
446
447
448
451
452
453
454
455
456
457
459
460
461
462
463
466
467
468
469
470
471
472
473
474
475
None value found
신영증권우 001725 2019 11013 None
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

477
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

478
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

479
480
481
482
483
484
485
486
487
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
514
516
517
518
519
521
523
524
525
526
527
529
532
533
534
535
537
538
540
541
542
543
545
546
548
549
550
551
552
553
554
556
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

557
558
559
561
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

562
563
564
565
566
567
568
569
570
571
572
573
575
576
578
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

579
580
582
584
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

588
589
None value found
대신증권우 003545 2019 11012 None
None value found
대신증권2우B 003547 2019 11012 None
592
None value found
유화증권우 003465 2019 11012 None
594
595
597
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

598
599
600
601
602
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

603
604
605
606
607
608
609
610
611
612
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

613
None value found
신영증권우 001725 2019 11014 None
615
616
617
618
619
620
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

621
622
None value found
대교우B 019685 2019 11014 None
625
627
629
630
631
632
634
635
636
637
638
639
640
642
643
644
645
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

646
647
649
650
651
652
653
654
655
656
657
658
659
None value found
현대차3우B 005389 2019 11014 None
None value found
현대차2우B 005387 2019 11014 None
None value found
현대차우 005385 2019 11014 None
663
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

664
665
666
667
668
669
670
671
673
674
None value found
신영증권우 001725 2019 11014 None
676
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

677
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

678
679
682
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

706
707
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
731
732
733
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

735
736
737
738
739
740
741
742
743
744
745
746
747
749
750
751
752
753
754
755
756
757
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

758
759
761
762
763
764
765
766
767
768
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

769
770
771
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

772
773
775
777
778
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

779
None value found
SK네트웍스우 001745 2020 11011 None
781
782
783
784
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
804
805
806
807
809
810
811
812
813
814
815
817
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
838
839
842
843
844
845
846
847
848
851
852
853
854
855
856
857
858
859
860
861
863
864
865
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

866
870
871
872
873
876
877
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

878
879
880
881
883
884
885
886
887
888
889
None value found
신영증권우 001725 2020 11011 None
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
916
917
918
919
920
921
922
923
924
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

925
926
927
928
930
931
932
934
935
936
937
938
939
940
941
942
943
944
945
948
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

951
952
953
954
955
956
957
958
959
960
961
962
963
964
966
968
969
970
971
972
973
974
976
977
978
979
980
981
982
983
984
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

985
987
988
989
990
991
992
993
995
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1010
1011
1012
1013
1016
1017
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1018
None value found
유화증권우 003465 2020 11011 None
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1044
1045
1046
1047
1048
1050
1051
1052
1053
1055
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1081
1082
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1098
1099
1100
1101
1102
1103
1104
1106
1107
1108
1110
1111
1112
1115
1116
1117
1118
1119
1121
1122
1123
1124
1125
1126
1127
1128
1129
1131
1133
1134
1135
1136
1137
1138
1139
1141
1142
1143
1144
1145
1147
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1161
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1162
1163
1164
1165
1166
1173
1177
1178
1179
1180
1181
1182
1185
1186
1187
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1199
1200
1201
1202
1203
1204
1205
1207
1208
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1209
1210
1211
1212
1213
1214
1215
1216
1220
1221
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1238
1239
1240
1241
1242
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1243
1244
1245
1246
1247
1248
1249
1250
1251
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1252
1253
1254
1255
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1256
1257
1258
1259
1260
1261
1262
1267
None value found
신영증권우 001725 2020 11012 None
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1300
1301
1302
1304
1305
1306
1307
None value found
대교우B 019685 2020 11014 None
1310
1311
1312
1313
1314
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1315
1316
1317
1318
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1344
1345
1346
1347
1348
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1349
1350
1351
1353
1354
1355
1356
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1373
1374
1375
1376
1377
None value found
신영증권우 001725 2021 11011 None
1379
1380
1381
1382
1383
1384
1385
1387
1388
1389
1390
1391
1392
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1395
1396
1397
1398
None value found
신영증권우 001725 2021 11011 None
1400
1401
1402
1403
1404
1405
1406
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1407
1408
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1428
1429
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1430
1431
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1432
1433
1434
1435
1436
1437
1439
1440
1441
1443
1444
1446
1447
1448
1449
1450
1451
1452
1453
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1454
1455
1456
1457
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1458
1459
1460
None value found
LG우 003555 2021 11011 None
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
None value found
신영증권우 001725 2021 11013 None
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1537
1538
1539
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1540
1542
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1543
1544
1545
1546
1547
1548
1549
1552
1553
1554
1555
1556
1557
1558
None value found
신영증권우 001725 2021 11012 None
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1574
1575
1576
1577
1578
1579
1580
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1581
1582
1583
1584
1585
1586
1588
1589
1590
1591
1592
1594
1595
1596
1597
1598
1599
1600
1602
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1603
1604
1605
1606
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1609
1610
1611
1612
1613
1614
1615
1616
1617
1620
1621
1622
1623
1624
1625
None value found
미래에셋증권2우B 00680K 2021 11012 None
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1627
1628
1629
1630
1631
1632
1633
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1659
1660
1661
1662
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1663
1664
1666
1667
1668
1669
1670
1671
1672
1673
1674
None value found
대교우B 019685 2021 11014 None
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1699
1700
1701
1702
1703
1704
None value found
현대차우 005385 2021 11014 None
None value found
현대차3우B 005389 2021 11014 None
None value found
현대차2우B 005387 2021 11014 None
1708
1709
1710
1711
1712
1713
1714
1715
1716
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1717
1718
1719
1721
1722
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1723
1724
1725
1726
1727
1728
1729
1731
1732
1733
1734
1735
1736
1737
1738
1739
1741
1743
1744
1745
1746
1747
1748
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1749
1750
1751
1752
1753
1754
1755
1756
1757
1759
1760
1761
1762
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1774
1775
1776
1777
1778
1779
1780
1782
1783
1784
1786
1787
1788
1789
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1790
1791
1792
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1793
1794
1795
1796
1797
1798
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1825
1826
1827
1828
1829
1830
1831
1832
1833
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1834
1835
1836
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1849
1850
1853
1856
1857
1858
1859
1860
1861
1862
1863
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1864
1865
1867
1870
1871
1873
1874
1876
1877
1878
1879
1880
1881
1882
1883
1884
1886
1887
1888
1889
1890
1891
1892
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1893
1895
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1896
1897
1898
1899
1901
1902
1903
1904
1905
1906
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1918
1919
1920
1922
1923
1924
1925
1926
1927
1928
1929
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
None value found
신영증권우 001725 2022 11013 None
1953
1954
1955
1956
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

1974
1975
1976
1977
1978
None value found
DL이앤씨2우(전환) 37550L 2022 11013 None
None value found
DL이앤씨우 37550K 2022 11013 None
1982
1983
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2005
2006
2007
2008
2009
2010
2011
2013
2015
2016
2017
2018
2019
2021
2022
2023
2024
2026
2027
2028
2029
2030
2031
2032
2034
2035
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2058
2059
2060
2061
2062
2064
2065
2066
2067
2068
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083
2084
2085
2086
2087
2088
2089
2090
2091
2092
2093
2094
2095
2096
2097
2099
2100
2101
2102
2103
2104
2105
2106
2107
2108
2109
2110
2111
2112
2113
2114
2115
2116
2117
2118
2119
2120
2121
2122
2124
2125
2126
2127
2128
2129
2131
2132
2133
2134
2135
2136
2139
2140
2141
2142
2143
2144
2145
2146
2147
2148
2149
2150
2151
2152
2153
2154
2155
2156
2157
2158
2160
2161
2162
2164
2165
2166
2167
2168
2169
2170
2171
2173
2174
2175
2176
2177
2178
2179
2180
2181
2182
2183
2184
2185
2186
2187
2188
2189
2190
2191
2192
2193
2194
2195
2196
None value found
신영증권우 001725 2022 11012 None
2198
2199
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2200
2201
2202
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2203
2204
2205
2206
2208
2209
2210
2213
2214
2215
2216
2217
2218
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2219
2220
2221
2222
2224
2225
2226
2227
2228
2229
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2230
2231
2232
2233
2234
2235
2236
2237
2238
2239
2240
2241
2242
2243
2244
2245
2247
2248
2249
2250
2251
2252
2254
2255
2256
2257
2258
2259
2260
2261
2262
2263
2264
None value found
대교우B 019685 2022 11014 None
2267
2269
2270
2272
2273
2274
2275
2276
2277
2278
2279
2280
2281
2282
2283
2284
2285
2286
2287
2288
2289
2290
2291
2292
2293
2295
2296
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2297
2298
2299
2300
2301
2302
2303
2304
2305
2306
2307
2308
2309
2310
2311
2312
2313
2316
2317
2318
2319
2320
2321
2322
2323
2324
2325
2326
2327
2328
2329
2330
2333
2334
2335
2336
2337
2338
2340
2341
2342
2343
2344
2345
2346
2347
2348
2349
2350
2351
2352
2353
2354
2355
2356
2357
2358
2359
2360
2361
2362
2363
2364
2365
2366
2367
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2368
2369
2370
2371
2372
2373
2374
2375
2376
2377
2378
2379
2380
2381
2382
2383
2384
2385
2386
2387
2388
2389
2390
2391
2393
2394
2395
2396
2398
2399
2400
2401
2402
2403
2404
2405
2406
2407
2408
2409
2410
2411
2412
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2414
2415
2416
2417
2419
2420
2421
2422
2423
2424
2425
2426
2427
2428
2429
2430
2431
2432
2433
None value found
DL이앤씨2우(전환) 37550L 2023 11011 None
2435
None value found
DL이앤씨우 37550K 2023 11011 None
2437
2439
2440
2441
2442
2443
2444
2445
2446
2447
2448
2449
2450
2451
2453
2454
2455
2456
2457
2458
2459
2460
2461
2462
2463
2464
2465
2466
2467
2468
2469
2471
2472
2473
2474
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2475
2476
2477
2478
2479
2480
2481
2482
2483
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2484
2485
2486
2487
2488
2489
2490
2491
2492
2493
2494
2495
2496
2497
2498
2500
2501
2502
2503
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2504
2505
2506
2507
2508
2509
2510
2511
2512
2513
2514
2515
2516
2517
2518
2520
2521
2522
2523
2524
2525
2526
2527
2528
2529
2530
2531
2532
2533
2534
2535
2536
2537
2538
2539
2540
2541
2542
2543
2544
2545
2546
2547
2548
2549
2550
2551
2552
2553
2554
2555
2556
2557
2558
2559
2560
2561
2562
2563
2564
2565
2566
2567
2568
2569
2570
2571
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2572
2573
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2574
2575
2576
2578
2579
2580
2581
2582
2583
2584
2585
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2586
2587
2588
2589
2590
2592
2593
2594
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2595
2596
2597
2598
2599
2600
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2601
2602
2604
2605
2606
2607
2608
2609
2610
2611
2612
2613
2615
2616
2617
2618
2619
2620
2621
2622
2623
2624
2626
2627
2628
2629
2630
2631
2632
2633
2634
2635
2636
2637
2638
2639
2640
2641
2642
2643
2644
2645
2646
2647
2648
2649
2651
2652
2653
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2654
2655
2656
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2657
2658
2659
2660
2661
2662
2663
2664
2665
2666
2667
2668
2669
2670
2671
2672
2674
2675
2676
2677
2678
2679
2680
2681
2682
2683
2684
2685
2687
2688
2689
2690
2691
2692
2693
2694
2695
2696
2697
2698
2699
2700
2701
2702
2703
2705
2706
2707
2708
2709
2710
2711
2712
2714
2715
2716
2717
2719
2720
2721
2722
2723
2724
2725
2726
2727
2729
2730
2731
2732
2733
2734
2735
2736
2737
2738
2739
2740
2741
2742
2743
2744
2745
2746
2747
2748
2749
2750
2751
2752
2753
2754
2755
2756
2757
2758
2759
2760
2761
2762
2763
2764
2765
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2766
2767
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2768
2769
2770
2771
2772
2773
2774
2775
2776
2777
2778
2779
2780
2781
2782
2783
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2784
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2785
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2786
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2787
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2788
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2789
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2790
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2791
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2792
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2793
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2794
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2795
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2796
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2797
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2798
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2799
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2800
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2801
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2802
None value found
미래에셋증권2우B 00680K 2024 11011 None
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2804
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2805
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2806
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2807
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2808
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2809
{'status': '013', 'message': '조회된 데이타가 없습니다.'}

2810

,stock_code,thstrm_amount_당기순이익,thstrm_amount_매출액,thstrm_amount_영업이익,thstrm_amount_유동자산,frmtrm_amount_당기순이익,frmtrm_amount_매출액,frmtrm_amount_영업이익,frmtrm_amount_유동자산,사업연도,직전분기코드,종목명
0,003000,"4,063,475,583","35,152,927,119","2,113,707,872","118,980,796,170","6,016,108,379","33,871,151,935","3,275,331,761","124,241,376,017",2018,11013,부광약품
1,182690,"-1,071,487,418",NaN,"-1,030,819,223","9,464,333,214","-1,097,272,944",NaN,"-986,377,633","5,721,553,302",2018,11013,테라셈
2,232140,"9,260,812,198","62,437,348,924","8,895,294,963","156,305,718,032","1,423,155,755","32,781,657,113","3,004,303,664","86,884,365,940",2018,11013,와이씨
3,170030,"201,449,871","29,765,993,472","-104,408,039","67,986,881,495","709,227,193","33,506,272,809","1,602,888,208","56,587,164,126",2018,11013,현대공업
4,080220,"4,172,278,819","40,889,138,018","4,440,301,114","80,751,005,194","-47,104,679","20,430,085,391","1,398,539,972","78,950,549,023",2018,11013,제주반도체
...,...,...,...,...,...,...,...,...,...,...,...,...
2393,200670,"9,263,286,039","41,173,715,488","10,648,469,413","141,486,281,168","11,079,880,686","36,119,924,344","9,304,524,095","130,351,790,910",2024,11013,휴메딕스
2394,405100,"650,801,436","12,597,684,484","109,229,863","63,364,063,351","1,763,134,652","11,836,364,276","879,709,915","61,562,208,669",2024,11013,큐알티
2395,084110,"6,484,378,281","14,087,319,122","7,526,402,513","40,049,936,598","2,371,514,899","12,660,094,755","4,454,675,677","50,455,316,232",2024,11013,휴온스글로벌
2396,243070,"10,851,702,904","132,331,532,021","11,577,964,081","229,320,500,405","13,606,957,794","119,429,334,367","11,144,335,721","241,479,879,671",2024,11013,휴온스
2397,159010,"1,755,798,795","26,003,695,543","2,638,272,843","86,478,206,015","2,609,751,864","22,192,726,094","3,068,607,539","74,913,436,295",2024,11013,아스플로

In [397]:
full_data.to_csv('full_data.csv', index=False, encoding='utf-8')

In [373]:
result_df.to_csv('result_df.csv', index=False, encoding='utf-8')

In [375]:
print(len(no_corp_code_list))

41

In [398]:
finance_data = pd.read_csv('result_df.csv')
finance_data['stock_code'] = finance_data['stock_code'].astype(str).str.zfill(6)
finance_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2398 entries, 0 to 2397
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   stock_code           2398 non-null   object
 1   thstrm_amount_당기순이익  2392 non-null   object
 2   thstrm_amount_매출액    2307 non-null   object
 3   thstrm_amount_영업이익   2380 non-null   object
 4   thstrm_amount_유동자산   2378 non-null   object
 5   frmtrm_amount_당기순이익  2392 non-null   object
 6   frmtrm_amount_매출액    2307 non-null   object
 7   frmtrm_amount_영업이익   2380 non-null   object
 8   frmtrm_amount_유동자산   2378 non-null   object
 9   사업연도                 2398 non-null   int64
 10  직전분기코드               2398 non-null   int64
 11  종목명                  2398 non-null   object
dtypes: int64(2), object(10)
memory usage: 224.9+ KB

In [404]:
full_data = pd.read_csv('full_data.csv')
full_data['직전분기코드'].astype('int64')
full_data['사업연도'].astype('int64')
full_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2669 entries, 0 to 2668
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   공시일              2669 non-null   object
 1   종목코드             2669 non-null   object
 2   종목명              2669 non-null   object
 3   시장구분             2669 non-null   object
 4   직접/신탁            2669 non-null   object
 5   취득/처분            2669 non-null   object
 6   취득(처분)예정기간_시작일   2669 non-null   object
 7   취득(처분)예정기간_종료일   2669 non-null   object
 8   신고내역_수량          2669 non-null   int64
 9   신고내역_금액          2669 non-null   int64
 10  체결내역(누계)_수량      2667 non-null   float64
 11  체결내역(누계)_체결수량비율  2669 non-null   float64
 12  체결내역(누계)_금액      2667 non-null   float64
 13  분기               2669 non-null   int64
 14  사업연도             2669 non-null   int64
 15  직전분기             2669 non-null   int64
 16  직전분기코드           2669 non-null   int64
dtypes: float64(3), int64(6), object(8)
memory usage: 354.6+ KB

In [405]:
full_data_1 = pd.merge(left= full_data, right=finance_data, how = 'left', left_on = ['종목명','사업연도','직전분기코드','종목코드'], right_on=['종목명','사업연도','직전분기코드','stock_code'])
full_data_1

,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,...,직전분기코드,stock_code,thstrm_amount_당기순이익,thstrm_amount_매출액,thstrm_amount_영업이익,thstrm_amount_유동자산,frmtrm_amount_당기순이익,frmtrm_amount_매출액,frmtrm_amount_영업이익,frmtrm_amount_유동자산
0,2018-05-30,003000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,...,11013,003000,"4,063,475,583","35,152,927,119","2,113,707,872","118,980,796,170","6,016,108,379","33,871,151,935","3,275,331,761","124,241,376,017"
1,2018-05-31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,...,11013,182690,"-1,071,487,418",NaN,"-1,030,819,223","9,464,333,214","-1,097,272,944",NaN,"-986,377,633","5,721,553,302"
2,2018-06-01,232140,와이씨,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,2000000000,...,11013,232140,"9,260,812,198","62,437,348,924","8,895,294,963","156,305,718,032","1,423,155,755","32,781,657,113","3,004,303,664","86,884,365,940"
3,2018-06-01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,...,11013,170030,"201,449,871","29,765,993,472","-104,408,039","67,986,881,495","709,227,193","33,506,272,809","1,602,888,208","56,587,164,126"
4,2018-06-01,080220,제주반도체,KOSDAQ,직접,취득,2018/06/04,2018/09/01,100000,472000000,...,11013,080220,"4,172,278,819","40,889,138,018","4,440,301,114","80,751,005,194","-47,104,679","20,430,085,391","1,398,539,972","78,950,549,023"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2960,2024-05-24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,...,11013,200670,"9,263,286,039","41,173,715,488","10,648,469,413","141,486,281,168","11,079,880,686","36,119,924,344","9,304,524,095","130,351,790,910"
2961,2024-05-24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,...,11013,405100,"650,801,436","12,597,684,484","109,229,863","63,364,063,351","1,763,134,652","11,836,364,276","879,709,915","61,562,208,669"
2962,2024-05-24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,...,11013,084110,"6,484,378,281","14,087,319,122","7,526,402,513","40,049,936,598","2,371,514,899","12,660,094,755","4,454,675,677","50,455,316,232"
2963,2024-05-24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,...,11013,243070,"10,851,702,904","132,331,532,021","11,577,964,081","229,320,500,405","13,606,957,794","119,429,334,367","11,144,335,721","241,479,879,671"
2964,2024-05-27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,...,11013,159010,"1,755,798,795","26,003,695,543","2,638,272,843","86,478,206,015","2,609,751,864","22,192,726,094","3,068,607,539","74,913,436,295"

In [408]:
merged_full_data = full_data_1

,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액,분기,사업연도,직전분기,직전분기코드
count,2.965000e+03,2.965000e+03,2.963000e+03,2965.000000,2.963000e+03,2965.000000,2965.000000,2965.000000,2965.000000
mean,3.830967e+05,1.541387e+10,6.833415e+05,43.763487,1.436375e+10,2.419224,2020.947723,2.734570,11012.383474
std,1.383530e+06,6.166172e+10,1.648296e+06,48.356382,5.911967e+10,1.194892,1.737195,1.106981,1.191936
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,1.000000,2018.000000,1.000000,11011.000000
25%,0.000000e+00,1.679878e+09,1.079085e+05,0.000000,1.036795e+09,1.000000,2020.000000,2.000000,11011.000000
50%,0.000000e+00,3.000000e+09,2.532830e+05,0.000000,2.786898e+09,2.000000,2021.000000,3.000000,11012.000000
75%,3.000000e+05,6.764000e+09,5.945370e+05,100.000000,5.383631e+09,4.000000,2022.000000,4.000000,11014.000000
max,2.781002e+07,1.828200e+12,2.467000e+07,103.390000,1.733740e+12,4.000000,2024.000000,4.000000,11014.000000

In [409]:
merged_full_data.to_csv('merged_full_data_X.csv', index=False, encoding='utf-8')

In [410]:
merged_full_data_X = pd.read_csv('merged_full_data_X.csv')

In [411]:
pip install finance-datareader

Requirement already satisfied: finance-datareader in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (0.9.90)
Requirement already satisfied: pandas>=0.19.2 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from finance-datareader) (2.0.3)
Requirement already satisfied: requests>=2.3.0 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from finance-datareader) (2.31.0)
Requirement already satisfied: requests-file in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from finance-datareader) (2.0.0)
Requirement already satisfied: lxml in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from finance-datareader) (5.2.1)
Requirement already satisfied: tqdm in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from finance-datareader) (4.65.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from pandas>=0.19.2->finance-datareader) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from pandas>=0.19.2->finance-datareader) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from pandas>=0.19.2->finance-datareader) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from pandas>=0.19.2->finance-datareader) (1.24.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from requests>=2.3.0->finance-datareader) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from requests>=2.3.0->finance-datareader) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from requests>=2.3.0->finance-datareader) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from requests>=2.3.0->finance-datareader) (2024.2.2)
Requirement already satisfied: six>=1.5 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=0.19.2->finance-datareader) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [416]:
merged_full_data_X['공시일'].dtypes
merged_full_data_X['공시일'] = pd.to_datetime(merged_full_data_X['공시일'])

In [428]:
!pip install exchange_calendars

Collecting exchange_calendars
  Downloading exchange_calendars-4.2.8-py3-none-any.whl.metadata (38 kB)
Requirement already satisfied: numpy in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from exchange_calendars) (1.24.3)
Requirement already satisfied: pandas>=1.1 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from exchange_calendars) (2.0.3)
Collecting pyluach (from exchange_calendars)
  Downloading pyluach-2.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: python-dateutil in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from exchange_calendars) (2.8.2)
Requirement already satisfied: pytz in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from exchange_calendars) (2023.3.post1)
Collecting toolz (from exchange_calendars)
  Downloading toolz-0.12.1-py3-none-any.whl.metadata (5.1 kB)
Collecting korean-lunar-calendar (from exchange_calendars)
  Downloading korean_lunar_calendar-0.3.1-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: tzdata>=2022.1 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from pandas>=1.1->exchange_calendars) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from python-dateutil->exchange_calendars) (1.16.0)
Downloading exchange_calendars-4.2.8-py3-none-any.whl (191 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 191.4/191.4 kB 6.8 MB/s eta 0:00:00
Downloading korean_lunar_calendar-0.3.1-py3-none-any.whl (9.0 kB)
Downloading pyluach-2.2.0-py3-none-any.whl (25 kB)
Downloading toolz-0.12.1-py3-none-any.whl (56 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.1/56.1 kB 7.0 MB/s eta 0:00:00
Installing collected packages: korean-lunar-calendar, toolz, pyluach, exchange_calendars
Successfully installed exchange_calendars-4.2.8 korean-lunar-calendar-0.3.1 pyluach-2.2.0 toolz-0.12.1

In [464]:

import pandas as pd
import FinanceDataReader as fdr
import exchange_calendars as ecals


def get_active_date(date):
    XKRX = ecals.get_calendar("XKRX") # 한국 코드
    if XKRX.is_session(date):
        return pd.to_datetime(date).strftime('%Y-%m-%d')
    else:
        return pd.to_datetime(XKRX.next_open(date)).strftime('%Y-%m-%d')

price_df = pd.DataFrame()

for index, row in merged_full_data_X.iterrows():
    code = row['종목코드']
    start_date = row['공시일']
    end_date_1month = get_active_date(start_date + pd.DateOffset(months=1))
    end_date_3month = get_active_date(start_date + pd.DateOffset(months=3))
    end_date_6month = get_active_date(start_date + pd.DateOffset(months=6))
    # print(end_date_6month.strftime('%Y-%m-%d'))
    price = fdr.DataReader(code, start_date, end_date_6month)['Close']
    # print(price)
    price_1month = price.loc[price.index == end_date_1month]
    price_3month = price.loc[price.index == end_date_3month]
    price_6month = price.loc[price.index == end_date_6month]
    
    # price_1month = price.iloc[str(end_data_1month)]
    # price_3month = price.loc[price['Date'] ==end_data_3month]
    # price_6month = price.loc[price['Date'] ==end_data_6month]
    df_list = [price_1month, price_3month, price_6month]
    df = pd.concat(df_list, axis=0)
    df = df.reset_index().T.reset_index().drop(columns='index').drop(index=0)
    new_columns = {
        0: 'price_1month',
        1: 'price_3month',
        2: 'price_6month'
    }
    df = df.rename(columns=new_columns).reset_index(drop=True)
    df['종목코드'] = code
    df['공시일'] = start_date
    # 인덱스를 제거하고 열 이름을 설정
    price_df = pd.concat([price_df, df], ignore_index=True)
    print(index)

price_df

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716
1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083
2084
2085
2086
2087
2088
2089
2090
2091
2092
2093
2094
2095
2096
2097
2098
2099
2100
2101
2102
2103
2104
2105
2106
2107
2108
2109
2110
2111
2112
2113
2114
2115
2116
2117
2118
2119
2120
2121
2122
2123
2124
2125
2126
2127
2128
2129
2130
2131
2132
2133
2134
2135
2136
2137
2138
2139
2140
2141
2142
2143
2144
2145
2146
2147
2148
2149
2150
2151
2152
2153
2154
2155
2156
2157
2158
2159
2160
2161
2162
2163
2164
2165
2166
2167
2168
2169
2170
2171
2172
2173
2174
2175
2176
2177
2178
2179
2180
2181
2182
2183
2184
2185
2186
2187
2188
2189
2190
2191
2192
2193
2194
2195
2196
2197
2198
2199
2200
2201
2202
2203
2204
2205
2206
2207
2208
2209
2210
2211
2212
2213
2214
2215
2216
2217
2218
2219
2220
2221
2222
2223
2224
2225
2226
2227
2228
2229
2230
2231
2232
2233
2234
2235
2236
2237
2238
2239
2240
2241
2242
2243
2244
2245
2246
2247
2248
2249
2250
2251
2252
2253
2254
2255
2256
2257
2258
2259
2260
2261
2262
2263
2264
2265
2266
2267
2268
2269
2270
2271
2272
2273
2274
2275
2276
2277
2278
2279
2280
2281
2282
2283
2284
2285
2286
2287
2288
2289
2290
2291
2292
2293
2294
2295
2296
2297
2298
2299
2300
2301
2302
2303
2304
2305
2306
2307
2308
2309
2310
2311
2312
2313
2314
2315
2316
2317
2318
2319
2320
2321
2322
2323
2324
2325
2326
2327
2328
2329
2330
2331
2332
2333
2334
2335
2336
2337
2338
2339
2340
2341
2342
2343
2344
2345
2346
2347
2348
2349
2350
2351
2352
2353
2354
2355
2356
2357
2358
2359
2360
2361
2362
2363
2364
2365
2366
2367
2368
2369
2370
2371
2372
2373
2374
2375
2376
2377
2378
2379
2380
2381
2382
2383
2384
2385
2386
2387
2388
2389
2390
2391
2392
2393
2394
2395
2396
2397
2398
2399
2400
2401
2402
2403
2404
2405
2406
2407
2408
2409
2410
2411
2412
2413
2414
2415
2416
2417
2418
2419
2420
2421
2422
2423
2424
2425
2426
2427
2428
2429
2430
2431
2432
2433
2434
2435
2436
2437
2438
2439
2440
2441
2442
2443
2444
2445
2446
2447
2448
2449
2450
2451
2452
2453
2454
2455
2456
2457
2458
2459
2460
2461
2462
2463
2464
2465
2466
2467
2468
2469
2470
2471
2472
2473
2474
2475
2476
2477
2478
2479
2480
2481
2482
2483
2484
2485
2486
2487
2488
2489
2490
2491
2492
2493
2494
2495
2496
2497
2498
2499
2500
2501
2502
2503
2504
2505
2506
2507
2508
2509
2510
2511
2512
2513
2514
2515
2516
2517
2518
2519
2520
2521
2522
2523
2524
2525
2526
2527
2528
2529
2530
2531
2532
2533
2534
2535
2536
2537
2538
2539
2540
2541
2542
2543
2544
2545
2546
2547
2548
2549
2550
2551
2552
2553
2554
2555
2556
2557
2558
2559
2560
2561
2562
2563
2564
2565
2566
2567
2568
2569
2570
2571
2572
2573
2574
2575
2576
2577
2578
2579
2580
2581
2582
2583
2584
2585
2586
2587
2588
2589
2590
2591
2592
2593
2594
2595
2596
2597
2598
2599
2600
2601
2602
2603
2604
2605
2606
2607
2608
2609
2610
2611
2612
2613
2614
2615
2616
2617
2618
2619
2620
2621
2622
2623
2624
2625
2626
2627
2628
2629
2630
2631
2632
2633
2634
2635
2636
2637
2638
2639
2640
2641
2642
2643
2644
2645
2646
2647
2648
2649
2650
2651
2652
2653
2654
2655
2656
2657
2658
2659
2660
2661
2662
2663
2664
2665
2666
2667
2668
2669
2670
2671
2672
2673
2674
2675
2676
2677
2678
2679
2680
2681
2682
2683
2684
2685
2686
2687
2688
2689
2690
2691
2692
2693
2694
2695
2696
2697
2698
2699
2700
2701
2702
2703
2704
2705
2706
2707
2708
2709
2710
2711
2712
2713
2714
2715
2716
2717
2718
2719
2720
2721
2722
2723
2724
2725
2726
2727
2728
2729
2730
2731
2732
2733
2734
2735
2736
2737
2738
2739
2740
2741
2742
2743
2744
2745
2746
2747
2748
2749
2750
2751
2752
2753
2754
2755
2756
2757
2758
2759
2760
2761
2762
2763
2764
2765
2766
2767
2768
2769
2770
2771
2772
2773
2774
2775
2776
2777
2778
2779
2780
2781
2782
2783
2784
2785
2786
2787
2788
2789
2790
2791
2792
2793
2794
2795
2796
2797
2798
2799
2800
2801
2802
2803
2804
2805
2806
2807
2808
2809
2810
2811
2812
2813
2814
2815
2816
2817
2818
2819
2820
2821
2822
2823
2824
2825
2826
2827
2828
2829
2830
2831
2832
2833
2834
2835
2836
2837
2838
2839
2840
2841
2842
2843
2844
2845
2846
2847
2848
2849
2850
2851
2852
2853
2854
2855
2856
2857
2858
2859
2860
2861
2862
2863
2864
2865
2866
2867
2868
2869
2870
2871
2872
2873
2874
2875
2876
2877
2878
2879
2880
2881
2882
2883
2884
2885
2886
2887
2888
2889
2890
2891
2892
2893
2894
2895
2896
2897
2898
2899
2900
2901
2902
2903
2904
2905
2906
2907
2908
2909
2910
2911
2912
2913
2914
2915
2916
2917
2918
2919
2920
2921
2922
2923
2924
2925
2926
2927
2928
2929
2930
2931
2932
2933
2934
2935
2936
2937
2938
2939
2940
2941
2942
2943
2944
2945
2946
2947
2948
2949
2950
2951
2952
2953
2954
2955
2956
2957
2958
2959
2960
2961
2962
2963
2964

     price_1month price_3month price_6month    종목코드        공시일
0           15581        16961        18139  003000 2018-05-30
1            2320         2230         1100  182690 2018-05-31
2            3835         4355         3065  232140 2018-06-01
3            3685         3135         2550  170030 2018-06-01
4            4580         4810         4240  080220 2018-06-01
...           ...          ...          ...     ...        ...
2960          NaN          NaN          NaN  200670 2024-05-24
2961          NaN          NaN          NaN  405100 2024-05-24
2962          NaN          NaN          NaN  084110 2024-05-24
2963          NaN          NaN          NaN  243070 2024-05-24
2964          NaN          NaN          NaN  159010 2024-05-27

[2965 rows x 5 columns]

In [465]:
price_df.to_csv('price_data_y.csv', index=False, encoding='utf-8')