In [1]:
import pandas as pd
import numpy as np

In [2]:
data_2018_2020 = pd.read_excel('2018-2020.xlsx')
data_2020_2022 = pd.read_excel('2020-2022.xlsx')
data_2022_2024 = pd.read_excel('2022-2024.xlsx')

/opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [33]:
data_2018_2020

,번호,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액
0,1,2020/05/27,218410,RFHIC,KOSDAQ,직접,취득,2020/05/28,2020/11/27,132275,5000000000,132275,100.0,4636499650
1,2,2020/05/26,25900,동화기업,KOSDAQ,직접,처분,2020/05/27,2020/05/27,250000,6400000000,250000,100.0,6080000000
2,3,2020/05/25,253590,네오셈,KOSDAQ,신탁,취득,2020/05/25,2020/11/24,0,2000000000,571366,0.0,1283324315
3,4,2020/05/25,79370,제우스,KOSDAQ,신탁,취득,2020/05/26,2021/05/25,0,2000000000,148412,0.0,1870236200
4,5,2020/05/20,25900,동화기업,KOSDAQ,직접,처분,2020/05/21,2020/05/21,500000,13200000000,500000,100.0,12540000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1192,1193,2018/06/01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2020/05/31,0,1000000000,16800,0.0,38690580
1193,1194,2018/06/01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,1000000000,51500,0.0,155690930
1194,1195,2018/06/01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,45200,0.0,199984125
1195,1196,2018/05/31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,470309,100.0,934335885
1196,1197,2018/05/30,3000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,1510786,100.0,42851934104

In [34]:
data_2020_2022

,번호,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액
0,1,2022/05/27,003550,LG,KOSPI,신탁,취득,2022/05/30,2024/12/31,0,500000000000,5590677.0,0.0,4.620222e+11
1,2,2022/05/27,003670,포스코퓨처엠,KOSPI,직접,취득,2022/05/30,2022/08/29,75187,9999871000,75187.0,100.0,9.645326e+09
2,3,2022/05/26,375500,DL이앤씨,KOSPI,신탁,취득,2022/05/26,2022/11/25,0,29000000000,647077.0,0.0,2.687100e+10
3,4,2022/05/26,37550L,DL이앤씨2우(전환),KOSPI,신탁,취득,2022/05/26,2022/11/25,0,29000000000,32299.0,0.0,1.076557e+09
4,5,2022/05/26,37550L,DL이앤씨2우(전환),KOSPI,신탁,취득,,,0,0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
786,787,2020/06/11,227840,현대코퍼레이션홀딩스,KOSPI,신탁,취득,2020/06/12,2020/12/11,0,3000000000,290000.0,0.0,2.985962e+09
787,788,2020/06/10,251370,와이엠티,KOSDAQ,직접,처분,2020/06/11,2020/06/11,80570,2167333000,80570.0,100.0,2.167333e+09
788,789,2020/06/05,006800,미래에셋증권,KOSPI,직접,취득,2020/06/08,2020/09/07,16000000,108600000000,16000000.0,100.0,1.108164e+11
789,790,2020/06/01,302920,더콘텐츠온,KONEX,신탁,취득,2020/06/01,2020/11/30,0,100000000,1188.0,0.0,1.241460e+07
790,791,2020/05/29,003410,쌍용C&E,KOSPI,신탁,취득,2020/06/01,2020/12/01,0,30000000000,3014405.0,0.0,1.568692e+10

In [35]:
data_2022_2024

,번호,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액
0,1,2024/05/27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0,0.0,0
1,2,2024/05/24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,0,0.0,0
2,3,2024/05/24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,0,0.0,0
3,4,2024/05/24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0,0.0,0
4,5,2024/05/24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973,974,2022/06/07,086900,메디톡스,KOSDAQ,직접,취득,2022/06/08,2022/09/05,39777,4999968900,39777,100.0,4574169500
974,975,2022/06/03,039440,에스티아이,KOSDAQ,신탁,취득,2022/06/03,2022/12/02,0,3000000000,159600,0.0,2984925950
975,976,2022/06/02,307870,비투엔,KOSDAQ,신탁,취득,2022/06/02,2022/12/02,0,2000000000,713194,0.0,1448972590
976,977,2022/05/31,236810,엔비티,KOSDAQ,신탁,취득,2022/06/02,2022/12/01,0,3500000000,430273,0.0,3492828520
977,978,2022/05/30,017650,대림제지,KOSDAQ,직접,취득,2022/05/31,2022/08/30,100000,959000000,100000,100.0,855555160

In [3]:
print(data_2018_2020.shape)
print(data_2020_2022.shape)
print(data_2022_2024.shape)

(1197, 14)
(791, 14)
(978, 14)

In [4]:
full_data = pd.concat([data_2018_2020, data_2020_2022, data_2022_2024], ignore_index=True)

In [46]:
full_data.columns

Index(['번호', '공시일', '종목코드', '종목명', '시장구분', '직접/신탁', '취득/처분', '취득(처분)예정기간_시작일',
       '취득(처분)예정기간_종료일', '신고내역_수량', '신고내역_금액', '체결내역(누계)_수량',
       '체결내역(누계)_체결수량비율', '체결내역(누계)_금액'],
      dtype='object')

In [5]:
full_data = full_data.sort_values(by='공시일', ascending=True).reset_index()
full_data = full_data.drop(columns=['index','번호'])

In [6]:
full_data['종목코드'] = full_data['종목코드'].astype(str).str.zfill(6)
full_data

,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액
0,2018/05/30,003000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,1510786.0,100.0,4.285193e+10
1,2018/05/31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,470309.0,100.0,9.343359e+08
2,2018/06/01,232140,와이씨,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,2000000000,437256.0,0.0,1.993199e+09
3,2018/06/01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,45200.0,0.0,1.999841e+08
4,2018/06/01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2020/05/31,0,1000000000,16800.0,0.0,3.869058e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,2024/05/24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,0.0,0.0,0.000000e+00
2962,2024/05/24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,0.0,0.0,0.000000e+00
2963,2024/05/24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00
2964,2024/05/24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00
2965,2024/05/27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00

In [27]:
company_list = full_data['종목명'].unique()
print(len(company_list))

1105

In [7]:
full_data.to_csv('full_data.csv', index=False, encoding='utf-8')

In [8]:
full_data = pd.read_csv('full_data.csv')

In [9]:
import requests
import pandas as pd
from datetime import datetime

# API key and base URL
API_KEY = '6e613b286881d7618be53b0237ead54a9751e26e'
BASE_URL_Multi= "https://opendart.fss.or.kr/api/fnlttMultiAcnt.json	"
BASE_URL_SINGLE = "https://opendart.fss.or.kr/api/fnlttSinglAcntAll.json"

In [182]:
def get_data(url, params):
    print(params)
    response = requests.get(url, params=params)
    data = response.json()
    print(data)
    if 'Data' in data and 'Data' in data['Data']:
        return pd.DataFrame(data['Data']['Data'])
    elif 'Data' in data:
        return pd.DataFrame(data['Data'])
    else:
        print("Error fetching data")
        return None

In [36]:
import pandas as pd
import xmltodict

def unique_code_xml_to_dataframe(xml_file):
    # XML 파일을 읽기
    with open(xml_file, 'r', encoding='utf-8') as file:
        xml_content = file.read()
    
    # XML을 파이썬 딕셔너리로 변환
    xml_dict = xmltodict.parse(xml_content)
    
    # 'result' 안의 'list'를 추출
    records = xml_dict['result']['list']
    
    # DataFrame 생성
    df = pd.DataFrame(records)
    
    return df

In [107]:
xml_file = 'CORPCODE.xml'

# XML을 DataFrame으로 변환
unique_code_df = unique_code_xml_to_dataframe(xml_file)
unique_code_df

       corp_code          corp_name stock_code modify_date
0       00434003                 다코       None    20170630
1       00434456               일산약품       None    20170630
2       00430964              굿앤엘에스       None    20170630
3       00432403               한라판지       None    20170630
4       00388953  크레디피아제이십오차유동화전문회사       None    20170630
...          ...                ...        ...         ...
106927  01835069                아로하       None    20240510
106928  01839199            호프인터내셔널       None    20240510
106929  01823392            포스텍네트웍스       None    20240510
106930  01837003         농업회사법인복순도가       None    20240510
106931  01785904           스튜디오에피소드       None    20240510

[106932 rows x 4 columns]

In [222]:
full_data = full_data.drop_duplicates(subset=['종목명','종목코드','공시일'])
full_data

,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액
0,2018/05/30,003000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,1510786.0,100.0,4.285193e+10
1,2018/05/31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,470309.0,100.0,9.343359e+08
2,2018/06/01,232140,와이씨,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,2000000000,437256.0,0.0,1.993199e+09
3,2018/06/01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,45200.0,0.0,1.999841e+08
5,2018/06/01,080220,제주반도체,KOSDAQ,직접,취득,2018/06/04,2018/09/01,100000,472000000,100000.0,100.0,5.059698e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,2024/05/24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,0.0,0.0,0.000000e+00
2962,2024/05/24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,0.0,0.0,0.000000e+00
2963,2024/05/24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00
2964,2024/05/24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00
2965,2024/05/27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00

In [223]:
quarter_code = {
    1: '11013',
    2: '11012',
    3: '11014',
    4: '11011'
}

full_data['공시일'] = pd.to_datetime(full_data['공시일'])
full_data['분기'] = pd.to_datetime(full_data['공시일']).apply(lambda x: (x.month-1)//3+1)
full_data['분기코드'] = full_data['분기'].map(quarter_code)
full_data['사업연도'] = full_data['공시일'].dt.year
full_data

,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액,분기,분기코드,사업연도
0,2018-05-30,003000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,1510786.0,100.0,4.285193e+10,2,11012,2018
1,2018-05-31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,470309.0,100.0,9.343359e+08,2,11012,2018
2,2018-06-01,232140,와이씨,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,2000000000,437256.0,0.0,1.993199e+09,2,11012,2018
3,2018-06-01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,45200.0,0.0,1.999841e+08,2,11012,2018
5,2018-06-01,080220,제주반도체,KOSDAQ,직접,취득,2018/06/04,2018/09/01,100000,472000000,100000.0,100.0,5.059698e+08,2,11012,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2961,2024-05-24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,0.0,0.0,0.000000e+00,2,11012,2024
2962,2024-05-24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,0.0,0.0,0.000000e+00,2,11012,2024
2963,2024-05-24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,11012,2024
2964,2024-05-24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,11012,2024
2965,2024-05-27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,11012,2024

In [224]:
def concat_unique_code(company_df, unique_code_df):
    company_df = company_df.merge(unique_code_df, left_on='종목명', right_on='corp_name', how='left')
    return company_df

In [225]:
def concat_unique_code_by_stock_code(company_df, unique_code_df):
    company_df = company_df.merge(unique_code_df, left_on='종목코드', right_on='stock_code', how='left')
    return company_df

In [226]:
full_data = concat_unique_code(full_data, unique_code_df)

In [227]:
full_data

,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액,분기,분기코드,사업연도,corp_code,corp_name,stock_code,modify_date
0,2018-05-30,003000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,1510786.0,100.0,4.285193e+10,2,11012,2018,00123718,부광약품,003000,20240403
1,2018-05-31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,470309.0,100.0,9.343359e+08,2,11012,2018,00411905,테라셈,182690,20221017
2,2018-06-01,232140,와이씨,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,2000000000,437256.0,0.0,1.993199e+09,2,11012,2018,01109539,와이씨,232140,20240425
3,2018-06-01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,45200.0,0.0,1.999841e+08,2,11012,2018,00164502,현대공업,170030,20230418
4,2018-06-01,080220,제주반도체,KOSDAQ,직접,취득,2018/06/04,2018/09/01,100000,472000000,100000.0,100.0,5.059698e+08,2,11012,2018,00447487,제주반도체,080220,20221207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,2024-05-24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,0.0,0.0,0.000000e+00,2,11012,2024,00614478,휴메딕스,200670,20220906
3353,2024-05-24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,0.0,0.0,0.000000e+00,2,11012,2024,01033591,큐알티,405100,20240227
3354,2024-05-24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,11012,2024,00228059,휴온스글로벌,084110,20221128
3355,2024-05-24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,11012,2024,01159853,휴온스,243070,20221007
3356,2024-05-27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,11012,2024,00561732,아스플로,159010,20220603

In [228]:
full_data = concat_unique_code_by_stock_code(full_data, unique_code_df)

In [229]:
full_data

,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,...,분기코드,사업연도,corp_code_x,corp_name_x,stock_code_x,modify_date_x,corp_code_y,corp_name_y,stock_code_y,modify_date_y
0,2018-05-30,003000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,...,11012,2018,00123718,부광약품,003000,20240403,00123718,부광약품,003000,20240403
1,2018-05-31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,...,11012,2018,00411905,테라셈,182690,20221017,00411905,테라셈,182690,20221017
2,2018-06-01,232140,와이씨,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,2000000000,...,11012,2018,01109539,와이씨,232140,20240425,01109539,와이씨,232140,20240425
3,2018-06-01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,...,11012,2018,00164502,현대공업,170030,20230418,00164502,현대공업,170030,20230418
4,2018-06-01,080220,제주반도체,KOSDAQ,직접,취득,2018/06/04,2018/09/01,100000,472000000,...,11012,2018,00447487,제주반도체,080220,20221207,00447487,제주반도체,080220,20221207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,2024-05-24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,...,11012,2024,00614478,휴메딕스,200670,20220906,00614478,휴메딕스,200670,20220906
3353,2024-05-24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,...,11012,2024,01033591,큐알티,405100,20240227,01033591,큐알티,405100,20240227
3354,2024-05-24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,...,11012,2024,00228059,휴온스글로벌,084110,20221128,00228059,휴온스글로벌,084110,20221128
3355,2024-05-24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,...,11012,2024,01159853,휴온스,243070,20221007,01159853,휴온스,243070,20221007
3356,2024-05-27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,...,11012,2024,00561732,아스플로,159010,20220603,00561732,아스플로,159010,20220603

In [230]:
full_data['corp_code'] = full_data['corp_code_x'].combine_first(full_data['corp_code_y'])

In [231]:
full_data

,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,...,사업연도,corp_code_x,corp_name_x,stock_code_x,modify_date_x,corp_code_y,corp_name_y,stock_code_y,modify_date_y,corp_code
0,2018-05-30,003000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,...,2018,00123718,부광약품,003000,20240403,00123718,부광약품,003000,20240403,00123718
1,2018-05-31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,...,2018,00411905,테라셈,182690,20221017,00411905,테라셈,182690,20221017,00411905
2,2018-06-01,232140,와이씨,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,2000000000,...,2018,01109539,와이씨,232140,20240425,01109539,와이씨,232140,20240425,01109539
3,2018-06-01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,...,2018,00164502,현대공업,170030,20230418,00164502,현대공업,170030,20230418,00164502
4,2018-06-01,080220,제주반도체,KOSDAQ,직접,취득,2018/06/04,2018/09/01,100000,472000000,...,2018,00447487,제주반도체,080220,20221207,00447487,제주반도체,080220,20221207,00447487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,2024-05-24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,...,2024,00614478,휴메딕스,200670,20220906,00614478,휴메딕스,200670,20220906,00614478
3353,2024-05-24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,...,2024,01033591,큐알티,405100,20240227,01033591,큐알티,405100,20240227,01033591
3354,2024-05-24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,...,2024,00228059,휴온스글로벌,084110,20221128,00228059,휴온스글로벌,084110,20221128,00228059
3355,2024-05-24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,...,2024,01159853,휴온스,243070,20221007,01159853,휴온스,243070,20221007,01159853
3356,2024-05-27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,...,2024,00561732,아스플로,159010,20220603,00561732,아스플로,159010,20220603,00561732

In [232]:
list_to_remove_index = full_data.loc[full_data['corp_code'].isna()].index.tolist()
list_to_remove = full_data.loc[full_data['corp_code'].isna()]
full_data = full_data.drop(list_to_remove_index)
full_data.loc[full_data['corp_code'].isna()]

Empty DataFrame
Columns: [공시일, 종목코드, 종목명, 시장구분, 직접/신탁, 취득/처분, 취득(처분)예정기간_시작일, 취득(처분)예정기간_종료일, 신고내역_수량, 신고내역_금액, 체결내역(누계)_수량, 체결내역(누계)_체결수량비율, 체결내역(누계)_금액, 분기, 분기코드, 사업연도, corp_code_x, corp_name_x, stock_code_x, modify_date_x, corp_code_y, corp_name_y, stock_code_y, modify_date_y, corp_code]
Index: []

[0 rows x 25 columns]

In [233]:
full_data

,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,...,사업연도,corp_code_x,corp_name_x,stock_code_x,modify_date_x,corp_code_y,corp_name_y,stock_code_y,modify_date_y,corp_code
0,2018-05-30,003000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,...,2018,00123718,부광약품,003000,20240403,00123718,부광약품,003000,20240403,00123718
1,2018-05-31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,...,2018,00411905,테라셈,182690,20221017,00411905,테라셈,182690,20221017,00411905
2,2018-06-01,232140,와이씨,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,2000000000,...,2018,01109539,와이씨,232140,20240425,01109539,와이씨,232140,20240425,01109539
3,2018-06-01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,...,2018,00164502,현대공업,170030,20230418,00164502,현대공업,170030,20230418,00164502
4,2018-06-01,080220,제주반도체,KOSDAQ,직접,취득,2018/06/04,2018/09/01,100000,472000000,...,2018,00447487,제주반도체,080220,20221207,00447487,제주반도체,080220,20221207,00447487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,2024-05-24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,...,2024,00614478,휴메딕스,200670,20220906,00614478,휴메딕스,200670,20220906,00614478
3353,2024-05-24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,...,2024,01033591,큐알티,405100,20240227,01033591,큐알티,405100,20240227,01033591
3354,2024-05-24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,...,2024,00228059,휴온스글로벌,084110,20221128,00228059,휴온스글로벌,084110,20221128,00228059
3355,2024-05-24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,...,2024,01159853,휴온스,243070,20221007,01159853,휴온스,243070,20221007,01159853
3356,2024-05-27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,...,2024,00561732,아스플로,159010,20220603,00561732,아스플로,159010,20220603,00561732

In [234]:
full_data = full_data.drop(columns=['corp_code_x','corp_code_y','corp_name_x','stock_code_x','modify_date_x','corp_name_y','stock_code_y','modify_date_y'], inplace=False)

In [235]:
full_data

,공시일,종목코드,종목명,시장구분,직접/신탁,취득/처분,취득(처분)예정기간_시작일,취득(처분)예정기간_종료일,신고내역_수량,신고내역_금액,체결내역(누계)_수량,체결내역(누계)_체결수량비율,체결내역(누계)_금액,분기,분기코드,사업연도,corp_code
0,2018-05-30,003000,부광약품,KOSPI,직접,처분,2018/05/31,2018/05/31,1510786,42851934104,1510786.0,100.0,4.285193e+10,2,11012,2018,00123718
1,2018-05-31,182690,테라셈,KOSDAQ,직접,처분,2018/06/01,2018/07/31,470309,832446930,470309.0,100.0,9.343359e+08,2,11012,2018,00411905
2,2018-06-01,232140,와이씨,KOSDAQ,신탁,취득,2018/06/01,2019/05/31,0,2000000000,437256.0,0.0,1.993199e+09,2,11012,2018,01109539
3,2018-06-01,170030,현대공업,KOSDAQ,신탁,취득,2018/06/01,2021/05/31,0,1000000000,45200.0,0.0,1.999841e+08,2,11012,2018,00164502
4,2018-06-01,080220,제주반도체,KOSDAQ,직접,취득,2018/06/04,2018/09/01,100000,472000000,100000.0,100.0,5.059698e+08,2,11012,2018,00447487
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,2024-05-24,200670,휴메딕스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,3000000000,0.0,0.0,0.000000e+00,2,11012,2024,00614478
3353,2024-05-24,405100,큐알티,KOSDAQ,신탁,취득,2024/05/24,2024/11/24,0,5000000000,0.0,0.0,0.000000e+00,2,11012,2024,01033591
3354,2024-05-24,084110,휴온스글로벌,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,11012,2024,00228059
3355,2024-05-24,243070,휴온스,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,11012,2024,01159853
3356,2024-05-27,159010,아스플로,KOSDAQ,신탁,취득,2024/05/27,2024/11/26,0,2000000000,0.0,0.0,0.000000e+00,2,11012,2024,00561732

### Test

In [237]:
def get_company_info_single(unique_code, year, quarter):
    print(unique_code, quarter, year)
    params = {
        'crtfc_key': API_KEY,
        'corp_code': unique_code,
        'bsns_year': year,
        'reprt_code': quarter,
        'fs_div': 'OFS'
    }
    return get_data(BASE_URL_SINGLE, params)

In [238]:
params = full_data.iloc[2][['corp_code','사업연도','분기코드']].tolist()
get_company_info_single(*params)

01109539 11012 2018
{'crtfc_key': '6e613b286881d7618be53b0237ead54a9751e26e', 'corp_code': '01109539', 'bsns_year': 2018, 'reprt_code': '11012', 'fs_div': 'OFS'}

In [189]:
!pip install opendartreader

Collecting opendartreader
  Using cached OpenDartReader-0.2.3-py3-none-any.whl.metadata (913 bytes)
Requirement already satisfied: pandas>=0.19.2 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from opendartreader) (2.0.3)
Requirement already satisfied: requests>=2.3.0 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from opendartreader) (2.31.0)
Requirement already satisfied: requests-file in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from opendartreader) (2.0.0)
Requirement already satisfied: lxml in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from opendartreader) (5.2.1)
Requirement already satisfied: beautifulsoup4 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from opendartreader) (4.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from pandas>=0.19.2->opendartreader) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from pandas>=0.19.2->opendartreader) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from pandas>=0.19.2->opendartreader) (2023.3)
Requirement already satisfied: numpy>=1.20.3 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from pandas>=0.19.2->opendartreader) (1.24.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from requests>=2.3.0->opendartreader) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from requests>=2.3.0->opendartreader) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from requests>=2.3.0->opendartreader) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from requests>=2.3.0->opendartreader) (2024.2.2)
Requirement already satisfied: soupsieve>1.2 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from beautifulsoup4->opendartreader) (2.5)
Requirement already satisfied: six>=1.5 in /opt/homebrew/Caskroom/miniconda/base/envs/ie471/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=0.19.2->opendartreader) (1.16.0)
Using cached OpenDartReader-0.2.3-py3-none-any.whl (27 kB)
Installing collected packages: opendartreader
Successfully installed opendartreader-0.2.3

In [239]:
import OpenDartReader

api_key = '6e613b286881d7618be53b0237ead54a9751e26e'

dart = OpenDartReader(api_key)

In [240]:

# for index, row in search_company_list.iterrows():
row = full_data.iloc[2]
corp = row['종목코드']
bsns_year = row['사업연도']
reprt_code = row['분기코드']
df = dart.finstate(corp, bsns_year, reprt_code)
filterd_df = df.loc[df['account_nm'].isin(['매출액', '영업이익', '당기순이익', '유동자산']) & (df['fs_nm'] == '재무제표')]
print(filterd_df.columns)
pivot_df = filterd_df.pivot(index = 'stock_code',columns='account_nm', values=['thstrm_amount','frmtrm_amount'])
pivot_df.columns = ['_'.join(col) for col in pivot_df.columns]
pivot_df = pivot_df.reset_index()
pivot_df

Index(['rcept_no', 'reprt_code', 'bsns_year', 'corp_code', 'stock_code',
       'fs_div', 'fs_nm', 'sj_div', 'sj_nm', 'account_nm', 'thstrm_nm',
       'thstrm_dt', 'thstrm_amount', 'frmtrm_nm', 'frmtrm_dt', 'frmtrm_amount',
       'ord', 'currency', 'thstrm_add_amount', 'frmtrm_add_amount'],
      dtype='object')

,stock_code,thstrm_amount_당기순이익,thstrm_amount_매출액,thstrm_amount_영업이익,thstrm_amount_유동자산,frmtrm_amount_당기순이익,frmtrm_amount_매출액,frmtrm_amount_영업이익,frmtrm_amount_유동자산
0,232140,"14,282,986,842","85,146,673,633","14,540,513,442","152,102,803,655","7,741,472,143","54,430,624,327","7,980,309,849","86,884,365,940"